# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d6d2f9e8f3cd769d0cfffa0304892ceff0570c70754fe393384a4720e92b2e0b5c9abc573646ab16d045d2e98d8bddea7342ab88d523d3d4fc74e7e63bd76f9

test:
  secret_key_base: 617b173a5880ac5b3d8ea9e3def02b586a97beb4c24446a93ceca41368d9b4ca984f2de2e2c3c4485a3416a4d836fe29a5cd96a3c483102aa1119b7b264b6123

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
